### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by samhh** [antonk52/cssmodules-language-server#1]
Hi there! I'm packaging this for the AUR. The package appears to be MIT-licensed per the npm manifest, so a license file included in the repo is customary. Cheers!

**Comment by antonk52** [comment]
Thanks for the issue, will add it shortly. Sorry for the delay

**Comment by antonk52** [comment]
Released to npm as v1.1.0 [github release notes](https://github.com/antonk52/cssmodules-language-server/releases/tag/v1.1.0)

Sorry for a delay, covid got to me 😅

**Comment by samhh** [comment]
Thank you, I hope you're feeling well! It knocked me off my feet back in November.
