### ISSUE TITLE
[lspconfig] Cannot access configuration for cssmodules_ls.

### ISSUE THREAD

**Issue by wizardels** [antonk52/cssmodules-language-server#10]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/17042376/153586968-0d73f80c-e91b-4f93-9dc7-b897a62ace42.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/17042376/153587028-007e94b2-93db-40bc-935d-f861d8c29cb2.png">

**Comment by antonk52** [comment]
Hi, not sure if this is an issue with `cssmodules-language-server` as I cannot reproduce it.

Please share versions of neovim and `cssmodules-language-server`.

**Comment by wizardels** [comment]
NVIM v0.6.0
cssmodules-language-server@1.2.1

**Comment by antonk52** [comment]
Still cannot reproduce with neither nvim v0.6.0 nor v0.6.1.

Can you verify that you have updated `nvim-lspconfig` plugin and that it contains `lua/lspconfig/server_configurations/cssmodules_ls.lua` file?

**Comment by wizardels** [comment]
Oh my, completely forgot I had to update. Thank you so much, sorry to waste your time!!
