### ISSUE TITLE
Neovim 8 changes

### ISSUE THREAD

**Issue by kecerud** [antonk52/cssmodules-language-server#11]
Hi there! Wanted to create a pull request to change the README but seems like I can't.

There have been changes in neovim 8 see: https://github.com/neovim/nvim-lspconfig/issues/1891#issuecomment-1157964108

And part of this snippet is deprecated:

```
require'lspconfig'.cssmodules_ls.setup {
    on_attach = function (client)
        -- avoid accepting `go-to-definition` responses from this LSP
        client.resolved_capabilities.goto_definition = false
        custom_on_attach(client)
    end,
}
```

`resolved_capabilities` is now `server_capabilities`

**Comment by antonk52** [comment]
Hi, thank you for flagging this. I would be happy to merge your pull request.

Can you share why you could not create a PR?

Should be the usual workflow: fork this repository -> make a change in your fork -> push to your fork -> create a PR in this repository

**Comment by kecerud** [comment]
@antonk52 Sorry about that at the end It was an issue on my side. All good now, created a PR here: https://github.com/antonk52/cssmodules-language-server/pull/12
