### ISSUE TITLE
`Package subpath './lib/stringifier' is not defined by "exports" `

### ISSUE THREAD

**Issue by musjj** [antonk52/cssmodules-language-server#21]
Tried to build this, but I'm getting this error when trying to trigger a definition jump:

```
Package subpath './lib/stringifier' is not defined by "exports" in /nix/store/22p2iznzn925vfrn8s91ljwag635s7s4-cssmodules-language-server-1.3.1/lib/node_modules/cssmodules-language-server/node_modules/postcss/package.json
```

It looks like that it's a postcss problem, but I'm not sure why it's happening.

**Comment by antonk52** [comment]
Hi, can you provide more info about what command did you run and the full output? From what is shared it is hard to infer what went wrong.

**Comment by antonk52** [comment]
I am going to close this issue due to lack of activity and a number of versions released since this issue was opened.

If this error still reproduces - feel free to reopen and share step to reproduce it.
