### ISSUE TITLE
Crash with commented tsconfig.json 

### ISSUE THREAD

**Issue by dhleong** [antonk52/cssmodules-language-server#23]
Looks to be caused by `lilconfig` [here](https://github.com/antonk52/cssmodules-language-server/blob/c0f618d0af64e3f251204250acbd9f39e1ef49b1/src/utils/resolveAliasedImport.ts#L53) using `require` to read JSON. Seems like we could use the `require-json5` module to override the default json file loader, something like:

```tsx
    const searcher = lilconfigSync('', {
        searchPlaces: ['tsconfig.json', 'jsconfig.json'],
        loaders: {
            '.json': require('require-json5'),
        },
    });
```

What do you think? Happy to put up a PR if you're open to this

**Comment by antonk52** [comment]
Hey, this makes sense. Happy to merge your PR. Though let's use [`json5`](https://www.npmjs.com/package/json5) directly without `require-json5`.
